-- Vessel · Reposición · esquema. Idempotente: se puede ejecutar varias veces.
-- Sin políticas RLS a propósito: solo el Worker (propietario de las tablas) accede.

CREATE TABLE IF NOT EXISTS settings (
  key   text PRIMARY KEY,
  value text
);

CREATE TABLE IF NOT EXISTS bars (
  id   integer PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE IF NOT EXISTS product_groups (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text    NOT NULL CHECK (char_length(name) BETWEEN 1 AND 40),
  sort       integer NOT NULL DEFAULT 0,
  created_at text    NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS product_groups_name_key ON product_groups (lower(name));

CREATE TABLE IF NOT EXISTS products (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text    NOT NULL,
  slug         text    NOT NULL,
  category     text    NOT NULL,
  status       text    NOT NULL DEFAULT 'confirmado',
  note         text,
  capacity_ml  integer,
  per_case     integer,
  photo        text,
  active       integer NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  out_of_stock integer NOT NULL DEFAULT 0 CHECK (out_of_stock IN (0, 1)),
  sort         integer NOT NULL DEFAULT 0,
  group_id     integer REFERENCES product_groups(id) ON DELETE SET NULL,
  group_order  integer,
  created_at   text    NOT NULL,
  updated_at   text    NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS products_slug_key ON products (slug);
CREATE INDEX IF NOT EXISTS idx_products_group ON products (group_id, group_order);

CREATE TABLE IF NOT EXISTS photos (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id),
  mime       text    NOT NULL,
  data       bytea   NOT NULL,
  created_at text    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_photos_product ON photos (product_id);

CREATE TABLE IF NOT EXISTS sessions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_date text    NOT NULL UNIQUE,
  created_at    text    NOT NULL,
  same_level    integer CHECK (same_level IN (0, 1)),
  notes         text
);

CREATE TABLE IF NOT EXISTS request_lines (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id    integer NOT NULL REFERENCES sessions(id),
  bar_id        integer NOT NULL REFERENCES bars(id),
  product_id    integer NOT NULL REFERENCES products(id),
  qty_requested integer NOT NULL,
  qty_cancelled integer NOT NULL DEFAULT 0,
  created_at    text    NOT NULL,
  updated_at    text    NOT NULL,
  created_by    text,
  claimed_by    text,
  claimed_at    text
);
CREATE INDEX IF NOT EXISTS idx_lines_session ON request_lines (session_id);

CREATE TABLE IF NOT EXISTS deliveries (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   integer NOT NULL REFERENCES sessions(id),
  bar_id       integer NOT NULL REFERENCES bars(id),
  product_id   integer NOT NULL REFERENCES products(id),
  line_id      integer REFERENCES request_lines(id),
  qty          integer NOT NULL,
  delivered_at text    NOT NULL,
  delivered_by text,
  source       text    NOT NULL DEFAULT 'lista',
  corrected    integer NOT NULL DEFAULT 0 CHECK (corrected IN (0, 1))
);
CREATE INDEX IF NOT EXISTS idx_deliveries_session ON deliveries (session_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_line ON deliveries (line_id);

CREATE TABLE IF NOT EXISTS stockouts (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id),
  started_at text    NOT NULL,
  ended_at   text,
  started_by text,
  ended_by   text
);
CREATE INDEX IF NOT EXISTS idx_stockouts_product ON stockouts (product_id);

CREATE TABLE IF NOT EXISTS audit (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at        text    NOT NULL,
  actor     text,
  entity    text    NOT NULL,
  entity_id integer,
  action    text    NOT NULL,
  before    text,
  after     text,
  reason    text
);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit (entity, id);

CREATE TABLE IF NOT EXISTS purchase_lists (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text NOT NULL,
  status     text NOT NULL DEFAULT 'borrador',
  params     text NOT NULL,
  lines      text NOT NULL,
  notes      text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS staff (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text    NOT NULL CHECK (char_length(name) BETWEEN 1 AND 40),
  active     integer NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  sort       integer NOT NULL DEFAULT 0,
  created_at text    NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS staff_name_key ON staff (lower(name));

-- RLS activado y sin políticas: anon/authenticated (API REST de Supabase) no ven nada.
ALTER TABLE settings       ENABLE ROW LEVEL SECURITY;
ALTER TABLE bars           ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE products       ENABLE ROW LEVEL SECURITY;
ALTER TABLE photos         ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions       ENABLE ROW LEVEL SECURITY;
ALTER TABLE request_lines  ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries     ENABLE ROW LEVEL SECURITY;
ALTER TABLE stockouts      ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit          ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff          ENABLE ROW LEVEL SECURITY;

-- Defensa adicional solo donde existen los roles de Supabase (en PGlite no existen).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA %I FROM anon, authenticated', current_schema());
    EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA %I FROM anon, authenticated', current_schema());
  END IF;
END $$;
