-- Almacén. Solo se añaden estructuras; la migración es idempotente.
CREATE TABLE IF NOT EXISTS stores (
  id integer PRIMARY KEY,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 40),
  kind text NOT NULL CHECK (kind IN ('local', 'central')),
  sort integer NOT NULL DEFAULT 0
);
INSERT INTO stores (id, name, kind, sort) VALUES
  (1, 'In Vessel', 'local', 10), (2, 'Out Vessel', 'central', 20)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS stock_counts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id integer NOT NULL REFERENCES stores(id),
  product_id integer NOT NULL REFERENCES products(id),
  qty integer NOT NULL CHECK (qty >= 0),
  expected integer,
  counted_at text NOT NULL,
  counted_by text,
  client_key text UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_stock_counts_last
  ON stock_counts (store_id, product_id, counted_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS trips (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status text NOT NULL DEFAULT 'abierto' CHECK (status IN ('abierto', 'hecho')),
  created_at text NOT NULL,
  created_by text,
  done_at text,
  done_by text
);
CREATE UNIQUE INDEX IF NOT EXISTS trips_one_open ON trips (status) WHERE status = 'abierto';

CREATE TABLE IF NOT EXISTS trip_lines (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id integer NOT NULL REFERENCES trips(id),
  product_id integer REFERENCES products(id),
  text text CHECK (text IS NULL OR char_length(text) BETWEEN 1 AND 80),
  qty_planned integer CHECK (qty_planned IS NULL OR qty_planned >= 0),
  qty_loaded integer CHECK (qty_loaded IS NULL OR qty_loaded >= 0),
  checked integer NOT NULL DEFAULT 0 CHECK (checked IN (0, 1)),
  source text NOT NULL DEFAULT 'apunte' CHECK (source IN ('sugerido', 'apunte')),
  created_at text NOT NULL,
  created_by text,
  CHECK (product_id IS NOT NULL OR text IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_trip_lines_trip ON trip_lines (trip_id);

CREATE TABLE IF NOT EXISTS stock_moves (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id),
  from_store_id integer REFERENCES stores(id),
  to_store_id integer REFERENCES stores(id),
  qty integer NOT NULL CHECK (qty > 0),
  kind text NOT NULL CHECK (kind IN ('entrada', 'traslado', 'rotura')),
  trip_id integer REFERENCES trips(id),
  created_at text NOT NULL,
  created_by text,
  note text,
  voided integer NOT NULL DEFAULT 0 CHECK (voided IN (0, 1)),
  voided_at text,
  voided_by text,
  void_reason text,
  CHECK (
    (kind = 'entrada' AND from_store_id IS NULL AND to_store_id IS NOT NULL)
    OR (kind = 'traslado' AND from_store_id IS NOT NULL AND to_store_id IS NOT NULL AND from_store_id <> to_store_id)
    OR (kind = 'rotura' AND from_store_id IS NOT NULL AND to_store_id IS NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_stock_moves_product ON stock_moves (product_id, created_at);
CREATE INDEX IF NOT EXISTS idx_deliveries_product_at ON deliveries (product_id, delivered_at);
INSERT INTO settings (key, value) VALUES ('trip_weeks', '2') ON CONFLICT (key) DO NOTHING;

ALTER TABLE stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_moves ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA %I FROM anon, authenticated', current_schema());
    EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA %I FROM anon, authenticated', current_schema());
  END IF;
END $$;

-- Fase 2: las líneas retiradas se conservan para el historial y la copia.
ALTER TABLE trip_lines ADD COLUMN IF NOT EXISTS removed integer NOT NULL DEFAULT 0 CHECK (removed IN (0, 1));
ALTER TABLE trip_lines ADD COLUMN IF NOT EXISTS removed_at text;
ALTER TABLE trip_lines ADD COLUMN IF NOT EXISTS removed_by text;
CREATE INDEX IF NOT EXISTS idx_stock_moves_trip ON stock_moves (trip_id);
CREATE INDEX IF NOT EXISTS idx_audit_almacen ON audit (id) WHERE entity = 'almacen';
