-- Fase 2: necesidades del próximo viaje. Idempotente; no borra datos ni historia.
-- Cada cambio de cantidad es una fila nueva; la anterior queda 'sustituido'.
CREATE TABLE IF NOT EXISTS need_adjustments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id),
  qty integer NOT NULL CHECK (qty BETWEEN 0 AND 10000),
  unit text NOT NULL CHECK (unit IN ('cajas', 'botellas')),
  per_case integer CHECK (per_case IS NULL OR per_case > 0),
  recommended integer CHECK (recommended IS NULL OR recommended >= 0),
  status text NOT NULL DEFAULT 'activo' CHECK (status IN ('activo', 'sustituido', 'pedido')),
  created_at text NOT NULL,
  created_by text,
  closed_at text,
  closed_by text,
  trip_id integer REFERENCES trips(id),
  trip_line_id integer REFERENCES trip_lines(id),
  CHECK (unit = 'botellas' OR per_case IS NOT NULL),
  CHECK (status <> 'pedido' OR trip_line_id IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS need_adjustments_one_active
  ON need_adjustments (product_id) WHERE status = 'activo';
CREATE INDEX IF NOT EXISTS idx_need_adjustments_product ON need_adjustments (product_id, id);
CREATE INDEX IF NOT EXISTS idx_trip_lines_product ON trip_lines (product_id) WHERE removed = 0;

ALTER TABLE need_adjustments ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA %I FROM anon, authenticated', current_schema());
    EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA %I FROM anon, authenticated', current_schema());
  END IF;
END $$;
